function(cpd_test name)
    set(src ${name}.cpp)
    set(target ${name}-test)
    add_executable(${target} ${src})
    set_target_properties(${target} PROPERTIES OUTPUT_NAME ${name})
    add_test(NAME ${name} COMMAND ${target})
    target_link_libraries(${target} PRIVATE Library-C++ ${ARGN} gtest_main)
    target_include_directories(${target} PRIVATE "${PROJECT_BINARY_DIR}")
endfunction()
